### ISSUE TITLE
[SUGGESTION] add colorscheme in picture

### ISSUE THREAD

**Issue by dibusure** [Manas140/paradise#12]
Add colorscheme picture like gruvbox
![example](https://camo.githubusercontent.com/410b3ab80570bcd5b470a08d84f93caa5b4962ccd994ebceeb3d1f78364c2120/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67)

**Comment by Manas140** [comment]
Sure, I'll try something similar to it.

**Comment by Manas140** [comment]
added with the commit f26699210c20057f37c4f00301e4ebbdd9dbb4fc
