### ISSUE TITLE
Make the theme installation portable

### ISSUE THREAD

**Issue by WitherCubes** [Manas140/paradise#2]
Don't force all configs to use Jetbrains Mono font by default and fix the mixed indentation. I will make a commit to fix this with the things I know, I will make the PR within a couple of hours.

**Comment by Manas140** [comment]
how are you going to solve it?

**Comment by WitherCubes** [comment]
Implementing some of the stuff like dracula but need to modify the install script.

**Comment by Manas140** [comment]
what is dracula?

**Comment by WitherCubes** [comment]
I meant the dracula theme - https://draculatheme.com

**Comment by bryant-the-coder** [comment]
@WitherCubes u are trying to make a new .sh file right? and renaming the theme's name and removing the settings. am i right? if i m wrong please correct me ヾ(•ω•`)o

**Comment by WitherCubes** [comment]
@bryant-the-coder I made a makefile instead of a shell script because it is easy to use than a shell script, if @Manas140 isn't fine with it I am happy to change it back to a shell script.

**Comment by bryant-the-coder** [comment]
what is the difference between a .sh and makefile??

**Comment by Manas140** [comment]
MakeFile needs make installed, so i suppose a sh file is better. as both comes with their own advantages and flaws so keep both, no need to remove one for other

**Comment by bryant-the-coder** [comment]
smart smart... rip windows user... they gotta copy and paste lmaoo

**Comment by WitherCubes** [comment]
@Manas140 I agree that both makefile and shell script has its pros and cons but any user is going to install make or it will be preinstalled. Moreover using makefile is idempotent and easy to manage than a shell script.

**Comment by Manas140** [comment]
1. yeah, most of them have make. 
2. yeah, make file is better to manage.

though, i feel i may need to keep install.sh. as:
![image](https://user-images.githubusercontent.com/64472354/147850694-c2c936d7-8ef3-42e9-9e07-f271fd6cf808.png)
1. can't get it to look like that and be as efficient as .sh file without any prior understanding of it.
![image](https://user-images.githubusercontent.com/64472354/147850736-fe98b04d-b379-4660-b9bf-2f521ffad39c.png)
2. sh is better to manage at the moment for me
I just started learning make file syntax cause i think it do be better for my projects. so yeah it will take time but will gradually reach there and may just need one file for installation. till then i keep both of them

**Comment by bryant-the-coder** [comment]
.sh will be better if i use linux. as it is commonly seen. but keeping both seems good to me

**Comment by WitherCubes** [comment]
I am fine having both too, I will help maintaining the makefile.

**Comment by bryant-the-coder** [comment]
i will take care of powershell and nvim theme if it is created i guess???

**Comment by Manas140** [comment]
thanks, if you get the windows or a good make file where code isn't repeated as much as it does now I'll remove the sh script as makefile would be better that day. Thanks for all the support you all show towards my project's

**Comment by WitherCubes** [comment]
No problem, I want to pass my time doing some useful things which benefits others.

**Comment by Manas140** [comment]
Is there a better way to contact you?

**Comment by WitherCubes** [comment]
I am mostly active on discord, my Discord tag is `WitherCubes#2513`.

**Comment by bryant-the-coder** [comment]
wanna create a server??

**Comment by WitherCubes** [comment]
Why create a server just for 2-3 people?

**Comment by bryant-the-coder** [comment]
lmaoo i mean for this repo

**Comment by WitherCubes** [comment]
The main point of the issue is fixed (#3), so I am closing this issue.
