### ISSUE TITLE
htop is not readable with paradise theme

### ISSUE THREAD

**Issue by prateekmedia** [Manas140/paradise#7]
Hi, This is a pretty good theme but the htop is not readable when using this theme, I have attached a screenshot below:
![2022-01-15_17-51](https://user-images.githubusercontent.com/41370460/149621601-534e3320-91c2-44de-bcf3-31fb5a6369ea.png)

Here the memory, swap values are not readable.

**Comment by Manas140** [comment]
i'll make the color a bit more lighter. will be visible that way

**Comment by Manas140** [comment]
![image](https://user-images.githubusercontent.com/64472354/149627231-cfde6ad0-1010-46b2-959c-a5d0fc944df7.png)
would that be ok?

**Comment by prateekmedia** [comment]
That looks great, Now the memory seems more readable.

**Comment by prateekmedia** [comment]
Wait, does before after looks pretty same?

I think it needs to be more lighter for swap and other values too.

**Comment by Manas140** [comment]
well try different color for htop, it looks better with the black night version
![image](https://user-images.githubusercontent.com/64472354/149627784-7641de23-1f13-4160-9877-517a1066df08.png)

**Comment by prateekmedia** [comment]
Thanks, I will close the issue then.
