### ISSUE TITLE
[port request] VS Code theme

### ISSUE THREAD

**Issue by SlinkousArt** [Manas140/paradise#9]
Would be nice to see an accompanying Code - OSS / Visual Studio Code theme eventually.

**Comment by Manas140** [comment]
Sure, I'll give it a try. Though there's no way I can assure that.

**Comment by datsfilipe** [comment]
If you haven't started yet and are accepting contributions, I could do that.

**Comment by Manas140** [comment]
Ah, that would be awesome... I'm working on some other stuff that isn't guaranteed to be, but yeah there's a chance. So, yeah go with it.

**Comment by Manas140** [comment]
Well it's officially there now thanks the @datsfilipe https://github.com/Manas140/paradise-vscode
